# -*- coding: utf-8 -*-
"""python project 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAOdTeAGR2JtHD8fZwfPJeHByi9NWK3L
"""

import pandas as pd
import random

names = ["Arun","Kavi","Ravi","Meena","Divya","John","Priya","Siva","Anu","Kumar"]

data = []

for i in range(250):
    student = {
        "Student_ID": i+1,
        "Name": random.choice(names),
        "Gender": random.choice(["Male","Female"]),
        "Department": random.choice(["CSE","IT","ECE"]),
        "Year": random.choice(["1st","2nd","3rd"]),
        "Maths": random.randint(40,100),
        "Science": random.randint(40,100),
        "English": random.randint(40,100),
        "Attendance": random.randint(50,100),
        "Internal": random.randint(0,25)
    }
    data.append(student)

df = pd.DataFrame(data)
df.head()

print(df.info())
print(df.describe())

df["Total"] = df["Maths"] + df["Science"] + df["English"]
df["Average"] = df["Total"] / 3

def grade(avg):
    if avg >= 75:
        return "A"
    elif avg >= 60:
        return "B"
    elif avg >= 50:
        return "C"
    else:
        return "Fail"

df["Grade"] = df["Average"].apply(grade)

df.head()

top_students = df.sort_values(by="Total", ascending=False).head(5)
print(top_students)

fail_students = df[df["Grade"] == "Fail"]
print(fail_students)

df.groupby("Department")["Average"].mean().plot(kind="bar")

df["Gender"].value_counts().plot(kind="pie", autopct="%1.1f%%")

import matplotlib.pyplot as plt

plt.hist(df["Total"], bins=20)
plt.title("Total Marks Distribution")
plt.show()

plt.scatter(df["Attendance"], df["Total"])
plt.xlabel("Attendance")
plt.ylabel("Total Marks")
plt.title("Attendance vs Marks")
plt.show()

print(df.groupby("Department")["Average"].mean())

print(df.groupby("Gender")["Average"].mean())